# helpcomplete zsh integration
# Generated by: helpcomplete init zsh
# Usage: eval "$(helpcomplete init zsh)"
if [[ -n "${HELPCOMPLETE_ZSH_LOADED:-}" ]]; then
  return 0
fi
HELPCOMPLETE_ZSH_LOADED=1

if ! (( ${+functions[compdef]} )); then
  autoload -Uz compinit && compinit -u
fi

HELPCOMPLETE_BIN="__HELPCOMPLETE_BIN__"

_helpcomplete_complete() {
  local cword out first_line sentinel
  cword=$((CURRENT - 1))

  if [[ -z "$HELPCOMPLETE_BIN" || ! -x "$HELPCOMPLETE_BIN" ]]; then
    _default && return 0
    return 1
  fi

  out=$("$HELPCOMPLETE_BIN" complete "$cword" -- "${words[@]}" 2>/dev/null </dev/null)
  if [[ $? -ne 0 || -z "$out" ]]; then
    _default && return 0
    return 1
  fi

  sentinel=$'\x01HELPCOMPLETE_DIRECTIVE\x01'
  first_line="${out%%$'\n'*}"

  case "$first_line" in
    "${sentinel}file")
      _files
      return 0
      ;;
    "${sentinel}directory")
      _files -/
      return 0
      ;;
  esac

  local -a candidates
  candidates=("${(@f)out}")
  if (( ${#candidates[@]} == 0 )); then
    _default && return 0
    return 1
  fi

  compadd -- "${candidates[@]}"
}

__HELPCOMPLETE_REGISTER__
