# helpcomplete bash integration
# Generated by: helpcomplete init bash
# Usage: eval "$(helpcomplete init bash)"
if [[ -n "${HELPCOMPLETE_BASH_LOADED:-}" ]]; then
  return 0 2>/dev/null || true
fi
HELPCOMPLETE_BASH_LOADED=1

HELPCOMPLETE_BIN="__HELPCOMPLETE_BIN__"

_helpcomplete_complete() {
  local cur cword out first_line sentinel
  COMPREPLY=()
  cword=$COMP_CWORD
  cur="${COMP_WORDS[$cword]}"

  if [[ -z "$HELPCOMPLETE_BIN" || ! -x "$HELPCOMPLETE_BIN" ]]; then
    return 0
  fi

  out=$("$HELPCOMPLETE_BIN" complete "$cword" -- "${COMP_WORDS[@]}" 2>/dev/null </dev/null)
  if [[ $? -ne 0 || -z "$out" ]]; then
    return 0
  fi

  sentinel=$'\x01HELPCOMPLETE_DIRECTIVE\x01'
  first_line="${out%%$'\n'*}"

  case "$first_line" in
    "${sentinel}file")
      COMPREPLY=( $(compgen -f -- "$cur") )
      return 0
      ;;
    "${sentinel}directory")
      COMPREPLY=( $(compgen -d -- "$cur") )
      return 0
      ;;
  esac

  local IFS=$'\n'
  COMPREPLY=( $(compgen -W "$out" -- "$cur") )
}

__HELPCOMPLETE_REGISTER__
